<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <!--SpringBoot Parent-->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.2</version>
        <relativePath/>
    </parent>

    <!-- Project coordinates -->
    <groupId>com.example</groupId>
    <artifactId>TradingBot</artifactId>
    <version>1.0-SNAPSHOT</version>

    <!-- Dependencies -->
    <dependencies>
    <!-- EJML -->
    <dependency>
        <groupId>org.ejml</groupId>
        <artifactId>ejml-all</artifactId>
        <version>0.43</version>
    </dependency>
    
    <!-- more recent yahho api-->
    <dependency>
        <groupId>org.json</groupId>
        <artifactId>json</artifactId>
        <version>20240303</version>
    </dependency>

    <!-- ojAlgo -->
    <dependency>
        <groupId>org.ojalgo</groupId>
        <artifactId>ojalgo</artifactId>
        <version>52.0.0</version>
    </dependency>
    <!--SpringBoot Dependency-->
    <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
</dependencies>
    <!-- Build plugins -->
    <build>
    <plugins>
        <!-- Maven compiler plugin -->
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.13.0</version>
            <configuration>
                <release>17</release>
            </configuration>
            </plugin>

        <!-- Exec plugin to run Java main classes -->
        <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.1.0</version>
            <configuration>
                <mainClass>com.example.TradingBotv2</mainClass>
            </configuration>
        </plugin>
    </plugins>
</build>
</project>